title: EhViewer 使用说明
description: EhViewer iOS、iPadOS 与 macOS 使用说明
url: https://liaowwxx.github.io
baseurl: /ehviewer-iosdemo
repository: liaowwxx/ehviewer-iosdemo

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
